# Generated by Django 5.1.6 on 2025-04-20 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_type', models.CharField(choices=[('free', 'Free Shipping'), ('flat_rate', 'Flat Rate')], default='flat_rate', max_length=10)),
                ('flat_rate_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum order amount for free shipping', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductShippingOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override_seller_settings', models.BooleanField(default=False)),
                ('shipping_type', models.CharField(choices=[('free', 'Free Shipping'), ('flat_rate', 'Flat Rate')], default='flat_rate', max_length=10)),
                ('flat_rate_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_override', to='products.product')),
            ],
        ),
    ]
