# Generated by Django 5.1.6 on 2025-04-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('activity_type', models.CharField(choices=[('view', 'View'), ('search', 'Search'), ('add_to_cart', 'Add to Cart'), ('purchase', 'Purchase')], max_length=50)),
                ('search_query', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'User Activities',
            },
        ),
    ]
